// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../AssemblyInfo.fs"
      "../Priems.fs"
      "../problem1.fs"
      "../problem2.fs"
      "../Problem3.fs"
      "../problem4.fs"
      "../Problem5.fs"
      "../problem6.fs"
      "../Problem8.fs"
      "../Problem9.fs"
      "../Problem10.fs"
      "../Problem11.fs"
      "../Problem49.fs"
